[package]
name = "retro486-task-progress"
version = "0.0.1"
authors = ["Russ Bernhardt <retro486@outlook.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
qmetaobject = "0.0.5"
cstr = "0.1.0"
cpp = "0.4"

[build-dependencies]
cpp_build = "0.4"
